-- 코드를 작성해주세요
SELECT 
  EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
  MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
  ID
FROM (
  SELECT 
    ID,
    SIZE_OF_COLONY,
    DIFFERENTIATION_DATE,
    EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) AS MAX_SIZE
  FROM ECOLI_DATA
) AS YEARLY_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;