-- 코드를 작성해주세요
SELECT 
  FI.ID, 
  FN.FISH_NAME, 
  FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN 
  ON FI.FISH_TYPE = FN.FISH_TYPE
JOIN (
  SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
  FROM FISH_INFO
  GROUP BY FISH_TYPE
) AS MAX_FISH
  ON FI.FISH_TYPE = MAX_FISH.FISH_TYPE AND FI.LENGTH = MAX_FISH.MAX_LENGTH
ORDER BY FI.ID;